config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users
  validates :name, uniqueness: true, presence: true
  validates :description, presence: true
  validates :price, presence: true
  # has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/alerts_controller.rb
alerts_controller.rb

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
skip_before_action :authenticate_user!, raise: false, only: :index
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :set_item, only: [:show, :edit, :update, :destroy]

 def index
    if params[:query].present?
      @query = params[:query]
      @items = Item.where("name iLike '%#{params[:query]}%'")
    else
      @items = Item.all
    end
  end

def show
end

def new
  @item = Item.new
end

def edit
end

def create

  @item = Item.new(item_params)
  @item.user = current_user
  if @item.save
    redirect_to item_path(@item)
  else
    render :new
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

end

private
def set_item
  @item= Item.find(params[:id])
end

def item_params
  params.require(:item).permit(:name, :description, :price, :picture_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :picture_url %>
    <%= f.text_field :picture_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control' %>
  </div>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="item-form">
        <h1>Edit your Coron'Article</h1>
        <div class="mt-3">
          <%= render "form", item: @item %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1584744982491-665216d95f8b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=900&q=60);">
  <div class="container">
    <h1>Welcome to Corona'Mart, world's first marketplace for Corona items.</h1>
    <p>Stay healthy and wealthy, sell and book your items.</p>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Corona Items</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @items.count %> items out of our <%= Item.count %> on our website.</p>
      <% else %>
        <p>All <%= Item.count %> items.</p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-4">
        <div class="item-card">
          <div class="item-card-image" style="background-image: url('<%= item.picture_url %>')"></div>
          <div class="item-card-content">
            <div class="item-card-title">
              <h4><%= item.name %></h4>
            </div>
            <p><%= item.description %></p>
            <div class="flex">
              <div class="flex ml-3">
                <i class="material-icons mr-2">€</i><%= item.price %>
              </div>
            </div>
          </div>
          <div class="item-card-actions">
            <%= link_to 'More info', item_path(item) %>
            <%= link_to 'Edit', edit_item_path(item), class: 'ml-3 text-warning' %>
            <%= link_to "Remove", item_path(item),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: 'ml-3 text-danger'
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="item-form">
        <h1>Add a new Coron'Article</h1>
        <div class="mt-3">
          <%= render "form", item: @item %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="map" style="background-image: url('<%= @item.picture_url %>')"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="item-show-card">
        <h1><%= @item.name %></h1>
        <p class="item-show-address"><%= @item.description %></p>
      </div>
      <div class="item-show-card">
        <h3>A bit more about this item...</h3>
        <p><%= @item.description %></p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%= @item.description %>&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C<%= @item.description %>&key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
      </div>
    </div>
    <div class="col-4">
      <div class="item-show-card">
        <h5>Book this item!</h5>
        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="item-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex ml-3">
            <i class="material-icons mr-2">euro_symbol</i> <%= @item.price %>
          </div>
        </div>
      </div>
      <div class="item-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>
          <div class="flex">
            <i class="fa fa-facebook-square fa-2x mr-2"></i>
            <i class="fa fa-twitter-square fa-2x mr-2"></i>
            <i class="fa fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>We got you covered!</h1>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Hand sanitizer" aria-label="Search" value="<%= params[:query] %>">
            <button class="btn btn-flat" type="submit">Search</button>
          </form>
          <li class="nav-item">
            <%= link_to "Add item", new_item_path, class: "btn" %>
          </li>
          <li class="nav-item dropdown">
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="btn">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>